services:
  db:
    image: mongo
    container_name: mongodb-container
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - ${DATABASE}:/data/db
    networks:
      - go-blog-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - db
    environment:
      - MONGO_URI=${MONGO_URI}
    networks:
      - go-blog-network

volumes:
  db-data:

networks:
  go-blog-network: